### ISSUE TITLE
Mysterious number: 9362

### ISSUE THREAD

**Issue by askerlee** [ContinuumIO/pyculib_sorting#6]
Hi I implemented a caffe (https://github.com/BVLC/caffe) module which uses `segsortpairs_float64()` to sort a long numpy array (6422528 elements) consisting of 49-element segments. So there are totally 131072 segments. If I sort the whole array, it always throws CUDA exceptions. Below is the diagnostic information cuda-memcheck outputs:
```
========= Invalid __global__ read of size 8
=========     at 0x00000788 in /home/xxxxxx/pyculib_sorting/thirdparty/moderngpu/include/kernels/../device/loadstore.cuh:77:void mgpu::KernelSegBlocksortIndices<mgpu::LaunchBoxVT<int=128, int=11, int=0, int=128, int=7, int=0, int=128, int=7, int=0>, bool=1, bool=1, double*, unsigned int*, double*, unsigned int*, mgpu::less<double>>(int=128, int=7, int, int const *, int const , int=0, int=128, int*, int=7)
=========     by thread (96,0,0) in block (256,0,0)
=========     Address 0x104bfdc0300 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuLaunchKernel + 0x2cd) [0x23cd8d]
=========     Host Frame:/usr/lib/pyculib_segsort.so [0x31f61]
=========     Host Frame:/usr/lib/pyculib_segsort.so [0x4fb03]
```
So I tried to reduce the sorted array size, and eventually found that, if I sort only 9362 segments (9362*49 elements), it runs smoothly. But if I sort 9363 segments, the exception appears.

A simple calculation: 9363 segments are 458787 elements. Considering the keys are double (8-bytes) and the values are uint32 (4-bytes), these elements take up 5505444 bytes, or 5376KB. This is not a huge array, though. 

Moreover, if I sort the above whole array in a standalone python script, everything is fine. I guess maybe caffe takes up some GPU RAM? But when the caffe script is running, the used RAM is 5785MiB, less than half of the total GPU RAM (12GB).

Could anyone give hints on what may cause this exception? Then I could dig deeper to find the culprit. Thank you very much.

Before fixing this problem, currently I can circumvent the error by splitting the whole array into 16 larger segments, and sorting each segment with `segsortpairs_float64()`. But this is not so convenient...

**Comment by askerlee** [comment]
Found out the actual cause: segsortpairs_float64() expects np.float64 input data (of course), but caffe uses float32 data. Then the function thought the input data were twice of the actual size, leading to memory access exceptions. A stupid mistake...

**Comment by stuartarchibald** [comment]
Thanks for the report, and also for reporting that you found the problem and fixed it, it is likely to help others. I'm also glad it is working for you now. You may wish to look at https://github.com/numba/pyculib/blob/master/pyculib/sorting/segsort.py to hint at type information etc.
